[package]
name = "stress-test"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = "1.16.0"
tokio = { version = "1.45.0", features = ["full"] }
rust_mc_proto_tokio = "0.1.18"
tokio-socks = "0.5.2"
simplelog = "0.12.2"
log = "0.4.27"
tracing-subscriber = "0.3.19"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]

[build]
rustflags = ["--cfg", "tokio_unstable"]
